
# This file was *autogenerated* from the file FFTpreproc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/bin/env sage

def FFTpreproc(m,B):
    data=[]
    Binv=[]
    assert (B[_sage_const_0 ].parent()).cardinality()==_sage_const_2 **m
    C=B[:]
    for level in range(_sage_const_0 ,m-_sage_const_1 ):
        G=[]
        D=[]
        c=C[-_sage_const_1 ]**(-_sage_const_1 )
        Binv.append(c)                                                                        
        for j in range(m-level-_sage_const_1 ):
            gam=c*C[j]                                                                      
            G.append(gam)     
            D.append(gam**_sage_const_2 -gam)
        G1=G[:]
        D1=D[:] 
        datacurrent=[G1,D1]
        data.append(datacurrent)
        C=D
    data.append(Binv)         
    return data

