
# This file was *autogenerated* from the file generatormatrixphi.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/bin/env sage

from a import *
from twostepinstance import *


#Generates the generator "matrix" (in this case a vector) over H where the i-th element is the image of the i-th unit vector. Elements are given in the basis 1,c,c^2,... where h(c)=0, for the representing polynomial h=instance.h
def generatormatrixphi_element(instance):
	Result=[]
	for i in range(instance.k):
		v=[GF(_sage_const_2 )(_sage_const_0 )]*(i)+[GF(_sage_const_2 )(_sage_const_1 )]+[GF(_sage_const_2 )(_sage_const_0 )]*(instance.k-i-_sage_const_1 )
		Result.append(phi_RMFE(v,instance))
	return Result


# Generates the generator matrix of phi, for a given instance. The matrix is a k x e binary matrix, with respect to the representation of GF(2^e) by polynomial instance.h

def generatormatrixphi_bits(instance):
	Result=[]
	genmat=generatormatrixphi_element(instance)
	return matrix(GF(_sage_const_2 ), instance.k, instance.e, lambda i, j: genmat[i][_sage_const_0 ]._vector_()[j])

def gener	

