
# This file was *autogenerated* from the file matrices.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_65 = Integer(65); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_33 = Integer(33); _sage_const_32 = Integer(32)#!/usr/bin/env sage

from generatormatrix import *

import os
import errno


def print_to_file(instance,data):
	switcher={'phi_matrix_bits':generatormatrixphi_element(instance), 'psi_matrix':generatormatrixpsi(instance), 'S_o_psi_matrix':generatormatrixS_o_psi(instance), 'h_poly':instance.h, 'phi_matrix_bits':generatormatrixphi_bits(instance), 'Ker_S_o_psi_basis': KerS_o_psi(instance), 'Ker_psi_basis':Kerpsi(instance)}

	option=switcher.get(data, lambda: 'Second argument should be phi_matrix_bits, psi_matrix, S_o_matrix, h_poly or phi_matrix_bits')

	filename = 'output_data/'+'RMFE'+'_'+str(instance.k)+'_'+str(instance.e)+'/'+data+'_'+str(instance.k)+'_'+str(instance.e)+'.txt'
	if not os.path.exists(os.path.dirname(filename)):
		try:
			os.makedirs(os.path.dirname(filename))
		except OSError as exc: 
			if exc.errno != errno.EEXIST:
				raise
	
	filet=open(filename, "w")
	
	filet.write(str(option))
		
	filet.close()	
		


List_instances=[twostepinstance(_sage_const_2 ,_sage_const_4 ,_sage_const_4 ,_sage_const_8 ),twostepinstance(_sage_const_2 ,_sage_const_3 ,_sage_const_8 ,_sage_const_16 ),twostepinstance(_sage_const_2 ,_sage_const_3 ,_sage_const_9 ,_sage_const_17 ),twostepinstance(_sage_const_2 ,_sage_const_4 ,_sage_const_8 ,_sage_const_16 ),twostepinstance(_sage_const_2 ,_sage_const_4 ,_sage_const_16 ,_sage_const_32 ),twostepinstance(_sage_const_3 ,_sage_const_6 ,_sage_const_16 ,_sage_const_32 ),
twostepinstance(_sage_const_3 ,_sage_const_8 ,_sage_const_16 ,_sage_const_32 ),twostepinstance(_sage_const_3 ,_sage_const_5 ,_sage_const_33 ,_sage_const_65 )]

#List_data=['phi_matrix_bits', 'psi_matrix', 'S_o_psi_matrix', 'h_poly', 'phi_matrix_bits', 'Ker_S_o_psi_basis', 'Ker_psi_basis']

List_data=['h_poly']

for instance in List_instances:
	for data in List_data:
		print_to_file(instance,data)


